name: Test GitHub Action
on: [push, workflow_dispatch]
jobs:
  DEV:
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello, DEV world!

  PROD:
    runs-on: ubuntu-latest
    needs:
    - DEV
    steps:
      - run: echo Hello, PROD world!